### ISSUE TITLE
resources目录下的mybatis目录是否可以删去

### ISSUE THREAD

**Issue by Q2035** [yeecode/EasyRPC#1]
mybatis目录下的文件是否多余。我在删除它们之后，运行程序并访问提供的路径（http://127.0.0.1:12310/getUserCount、http://127.0.0.1:12310/getUserInfo、http://127.0.0.1:12310/addUser、http://127.0.0.1:12310/querySchoolName），未发现异常。

**Comment by yeecode** [comment]
可以删除，这是从我的另一个项目（MatrixAuth）中错误带过来的MyBatis配置文件。
感谢提醒，我会很快进行更新。
