### ISSUE TITLE
看了知乎回答过来的，请教几个问题

### ISSUE THREAD

**Issue by kybetter** [yeecode/EasyRPC#3]
1、客户端是什么时候从服务端拿到函数映射列表的？

2、客户端组装好数据后，通过什么样的方式序列化数据？需要跟着服务端的规定来做吗？

比如：前端浏览器环境，我是序列化成 json 呢？还是用 form-url-encode ？还是有其它方式？

因为有的文章说的神乎其神的，还要二进制打包啥的，完全不知道他们要表述什么。

3、客户端用 POST 还是 GET 请求的方式？也是跟着服务端的规定来吗？

4、服务端处理完数据后，传给前端的数据格式，跟我们平常请求接口返回的数据格式是一样的吗？

**Comment by yeecode** [comment]
1、这是一个工程实践问题。往往需要搭建一个服务展示和下载的平台，单独完成这件事。
2、只要序列化和反序列化采用的机制一样即可。因为这两个过程都是RPC框架内部完成了，RPC框架可以很方便地做到这一点。
3、这个也是RPC框架决定的。只要接收方和发送方一致即可。不过，要是在Get和Post中选一个，那就选择走Post，因为前者能传输的数据长度有限。
4、这也不重要，只要客户端的RPC能够正常解开就好。

所以，序列化、发送，接收、反序列化，这些操作都在RPC框架中完成，只要RPC框架做到前后操作一致，就好了。具体采用什么协议，就看RPC框架自己的衡量了，并不是太关键。
